name = "ReachabilityModels"
uuid = "20aa409e-046b-4a69-a2fd-3a10e4fb9b33"
authors = ["Marcelo Forets"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"

[compat]
julia = "1.4"
ModelingToolkit = "3.15"
ReachabilityAnalysis = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
