name: CI

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
    branches:
      - master

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    env:
      JULIA_PKG_SERVER: ''
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Cache artifacts
        uses: julia-actions/cache@v1
      - name: Install dependencies & build package
        run: |
          julia --project --color=yes -e 'using Pkg;
              Pkg.add(url="https://github.com/JuliaReach/SpaceExParser.jl.git");
              Pkg.build(verbose=true)'
        shell: bash
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
